### ISSUE TITLE
Initial map loading - add loader

### ISSUE THREAD

**Issue by konrad-appsilon** [Appsilon/covid-hackathon#3]

**Comment by Alverga** [comment]
I have cloned this project, in this project there is the renv set, which means most of the packges were restored, but right now I have a problem with shiny package itself. Because of the time, I will leave a message to Pedro,asking for some guidance or insight on how to overcome this issue and add the loader to this project.

**Comment by Alverga** [comment]
I fixed the problem with Shiny package version to load locally installing a downgraded version of R (from 4.1.2 to 3.6.1). Actually, following a tutorial provided by Oleksandr Ponomarov. Te app locally, doesn't show the same load time than in production server at demo.appsilon.com, so I tryed 2 different approaches to solve the issue of adding a loader when loading the map. Both solutions were motivated, because leaflet map objects doesn't inform about ending his loading process, as pointed by Fernando Roa in issue #45 https://github.com/Appsilon/VisuaRISK/issues/45.The first solution uses shinyWidgets package along wih addSpinner() function.  The second solution I provided in code, uses a modalDialog() and taglists() along with the function withSpinner() (from the package shinycssloaders). To complete testing and reviewing I will need credentials and some guidance on how to publish through RS Connect at Appsilon and make a pull request after testing. For that I am reading Pedro Silva 's  material https://appsilon.getoutline.com/doc/deployment-aXrITTSHcI .

**Comment by Alverga** [comment]
As suggested by Pedro, I will take a look in sleep() function, to hold loading time and see if the loaders is working locally with leaflet, before deploying.

**Comment by Alverga** [comment]
I have concluded adding a loader, using package waiter. Which allows you define a poin of showing and hiding in server.R code. This was, so far, the best solution I found, since shinyWidgets and shinycssloaders packages seems to wait for a response from the object that is being loaded and leaflet maps doesn't reply when loading process is happening.

**Comment by Alverga** [comment]
Tested in the new server, demo.prod.appsilon.ai and worked with the loader added.
